container_tag: "{{ zuul.change }}-{{ zuul.patchset }}-{{ zuul.buildset[0:9] }}"
container_name: "opencontrailnightly/developer-sandbox"
container_target: "opencontrail/developer-sandbox"
sandbox_branch: "{{ zuul.branch }}"
